### ISSUE TITLE
webhook on* handlers should receive the whole events

### ISSUE THREAD

**Issue by zatziky** [amio-io/amio-sdk-js#48]
### Now

Webhook router sends just `data` to handlers via `routeEvent({event, data, timestamp})` and `invokeHandlers(data, timestamp, this.handlers[event])`

### After change
`routeEvent(webhookEvent)` and `invokeHandlers(webhookEvent, this.handlers[event])`

### Tasks
- [x] update readme.md
- [ ] change emit counterpart in websocket
- [x] increase the major version in package.json
- [ ] create tasks in all our projects using this SDK to update the package and make code changes
