### ISSUE TITLE
Endpoint: GET Contact

### ISSUE THREAD

**Issue by zatziky** [amio-io/amio-sdk-js#9]
docs: https://docs.amio.io/v1.0/reference#viber-get-contact

### Tasks
- [x] create a new request class in `lib/api/contact.js`
- [x] method `get(channelId, contactId)`
- [x] create test that will find a contact in `connector.test.js`
- [x] docs in readme.md
